version: '3'
services:
  advertising:
    image: advertising-image
    ports:
      - 8075:8075
    environment:
      - spring.application.name=Advertising
      - spring.config.import=optional:configserver:http://config-server:8888
    networks:
      - 8082

  chat:
    image: chat-image
    ports:
      - 8787:8787
    environment:
      - spring.application.name=chat
      - spring.datasource.url=jdbc:mysql://mysql:3306/chat?createDatabaseIfNotExist=true&useUnicode=true
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
    networks:
      - 8082

  config-server:
    image: your-config-server-image
    ports:
      - 8888:8888
    environment:
      - server.port=8888
      - spring.profiles.active=native
      - spring.application.name=config-server
      - spring.cloud.config.server.native.search-locations=classpath:/configurations
    networks:
      - 8080

  discovery:
    image: your-discovery-image
    environment:
      - spring.config.import=optional:configserver:http://config-server:8888
      - spring.application.name=discovery
    networks:
      - 8888

  gateway:
    image: your-gateway-image
    environment:
      - spring.application.name=gateway
      - spring.config.import=optional:configserver:http://config-server:8888
    networks:
      - 8888

  playstream:
    image: your-playstream-image
    ports:
      - 8091:8091
    environment:
      - server.port=8091
      - spring.config.import=optional:configserver:http://config-server:8888
      - spring.h2.console.enabled=true
      - spring.h2.console.path=/h2
      - spring.datasource.username=Aziz
      - spring.datasource.password=
      - spring.datasource.driver-class-name=org.h2.Driver
      - spring.datasource.url=jdbc:h2:./Database/Data/Game
      - spring.jpa.hibernate.ddl-auto=create
      - eureka.client.service-url.defaultZone=http://discovery:8761/eureka
      - eureka.client.register-with-eureka=true
      - spring.web.cors.allowed-origins=*
      - spring.web.cors.allowed-methods=*
      - spring.web.cors.allowed-headers=*
    networks:
      - 8091

tournament:
    build:
      context: ./tournament-microservice
    ports:
      - "8086:8086"
    environment:
      - spring.datasource.url=jdbc:mysql://db/WebTournoi?createDatabaseIfNotExist=true&useUnicode=true
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

db:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_DATABASE=chat
    - MYSQL_DATABASE=WebTournoi
  ports:
    - "3306:3306"

eureka:
  image: springcloud/eureka
  ports:
    - "8761:8761"
