#eureka:
# instance:
#  hostname: localhost
# client:
#  service-url:
#   defaultZone: http://localhost:8089/eureka/
server:
 port: 8787
spring:
 application:
  name: chat
 datasource:
  url: jdbc:mysql://localhost:3306/chat?createDatabaseIfNotExist=true&useUnicode=true
  username: root
  password:
 jpa:
   show-sql: true
   hibernate:
    ddl-auto: update
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQL5Dialect
